//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string NAME { get; set; }
        public string DISTRICT { get; set; }
        public string AMPHUR_ID { get; set; }
        public string PROVINCE_ID { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<int> ADDRESSTYPE_ID { get; set; }
        public string ZIPCODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual AddressType AddressType { get; set; }
    }
}
