//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int ID { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_TH { get; set; }
        public string LOCATION { get; set; }
        public string AMPHUR { get; set; }
        public string PROVINCE { get; set; }
        public string POSTCODE { get; set; }
        public string TELEPHONE { get; set; }
        public byte[] LOGO { get; set; }
        public byte[] RIGHT_LOGO_1 { get; set; }
        public byte[] RIGHT_LOGO_2 { get; set; }
    }
}
