//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerScan
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public byte[] LEFTFINGER1 { get; set; }
        public byte[] LEFTFINGER2 { get; set; }
        public byte[] LEFTFINGER3 { get; set; }
        public byte[] LEFTFINGER4 { get; set; }
        public byte[] LEFTFINGER5 { get; set; }
        public byte[] RIGHTFINGER1 { get; set; }
        public byte[] RIGHTFINGER2 { get; set; }
        public byte[] RIGHTFINGER3 { get; set; }
        public byte[] RIGHTFINGER4 { get; set; }
        public byte[] RIGHTFINGER5 { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
