//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferencePerson
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public string RELATIONSHIFT { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
    }
}
