//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSO
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string HOSPITAL_NAME { get; set; }
        public string PROVINCE_NAME { get; set; }
        public Nullable<bool> NOTINDATABASE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
