//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string POSITION { get; set; }
        public string SALARY { get; set; }
        public string PERIOD { get; set; }
        public string RESIGN_REASON { get; set; }
    }
}
