//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zipcode
    {
        public int ZIPCODE_ID { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string PROVINCE_ID { get; set; }
        public string AMPHUR_ID { get; set; }
        public string DISTRICT_ID { get; set; }
        public string ZIPCODE1 { get; set; }
    }
}
